#!/usr/bin/env python

import getpass

import playcl.app
import playcl.client

def main():
	"""
	Entry point of the script.
	"""

	app = playcl.app.PlayClApp()
	app.run()

if __name__ == '__main__':
	main()

